### ISSUE TITLE
VTGate in a cell doesn't see Keyspaces without replica in that particular cell

### ISSUE THREAD

**Issue by bernardhalas** [planetscale/vitess-operator#162]
Scenario: Vitess deployed via operator. Cluster contains 3 cells. Keyspace contains replica just in one of the cells (`zone1`): [cluster.yml](https://github.com/planetscale/vitess-operator/files/5677241/cluster.yml.txt)

Problem: VTGates in other two cells (`zone2`, `zone3`) do not have the visibility of the keyspace (i.e. `show databases` against VTGate in `zone2` and `zone3` doesn't list the keyspace).

Opening this one as an issue as per a relevant discussion on Slack.

**Comment by enisoc** [comment]
Unfortunately, this is a limitation in Vitess itself. VTGates look for keyspace info in their cell-local topology, and cell-local topology info is populated by VTTablets from that keyspace in that cell. If there are no tablets for a given keyspace in a given cell, then there's no one to populate the keyspace entry in that cell. It's definitely fixable, but the fix should be in Vitess rather than here in the operator.

**Comment by bernardhalas** [comment]
Thank you for the explanation of the behavior. From my perspective this issue can be closed now as the behavior is not buggy and matching the expectation.

**Comment by deepthi** [comment]
@bernardhalas could you create an issue on the vitess repo for this? thanks!
