### ISSUE TITLE
Allow opening Tablet port 15002 when Prometheus stats are enabled

### ISSUE THREAD

**Issue by henders** [planetscale/vitess-operator#34]
Currently even if you specify the below extraFlags for the Gateway or Tablets it won't function properly as the port won't be accessible by the prometheus (or Datadog) agents.
```
extraFlags:
        grpc_prometheus: "true"
```

We could add the ability to have an `extraPort` option, but that would have to be only applicable to the VTTablet container.

**Comment by enisoc** [comment]
We already expose port `15000` which is where most Prometheus metrics get published (under `/metrics`). Do the `grpc_prometheus` metrics not get published in the same place?

Even if they are served on a different port, it's usually not necessary to advertise a port on the Pod/Container spec in order to access it. The process can serve any port it wants and it will be accessible on the Pod IP. Is there some reason the scrapers need the port to be advertised and not just available?

If the problem is just that the vttablet Service doesn't have the right port, you could also create your own Service to select the existing Pods, without having to modify the operator.

**Comment by henders** [comment]
So I had been told that that flag explicitly exposed prometheus metrics on the `0:15002/metrics` URI, and I haven't checked if they look identical to Vitess's own `0:15000/metrics` which I'll do.

I had also thought that unless you expose the port, then processes outside the pod can't access that port. I'll go double-check that. The datadog agent picking up these metrics is running in a K8s Daemonset.

**Comment by henders** [comment]
Ah, going to close this. I hadn't understood that the Prometheus metrics were exposed under the same `--port` setting. So yes, you're right in that the localhost:15000/metrics are the same thing.  

The Helm Chart default was port 15002, hence my confusion :)
