### ISSUE TITLE
Allow extra Labels to be specified like the Annotations

### ISSUE THREAD

**Issue by henders** [planetscale/vitess-operator#35]
We currently support adding arbitrary Annotations to be added to all the components. In our company we require having specific labels added to our K8s pods to indicate things like the owning team names. 

Can we follow the annotations pattern and allow another map[string][string] for labels as well?

**Comment by enisoc** [comment]
I like this idea. You're right that it will probably look very similar to the existing custom annotation support. Would you be interested in working on this by chance? :)

**Comment by henders** [comment]
I was debating this alright... I'm trying to find how I can free up some of my time! :)

**Comment by evalsocket** [comment]
@enisoc @henders Would like to work on this. Can this be assigned to me?

**Comment by enisoc** [comment]
@evalsocket That would be great if you're interested in working on this! We should just make sure to agree on the design first.

@henders If we expanded the [API](https://vitess-operator.planetscale.dev/api/) to additionally have a `labels` field in all the places where we currently have an `annotations` field, would that satisfy your use case?

If so, then it should be very analogous to #7, just with labels instead of annotations.

**Comment by henders** [comment]
That would be great. And yes, adding a `labels` field everywhere there is an `annotations` field would absolutely solve our usecase!

**Comment by enisoc** [comment]
@henders Thanks for confirming!

@evalsocket It sounds like #7 should be a good template for this then. The author of that PR (@avaidyanatha) can help if you have any questions about it.
