### ISSUE TITLE
imagePullPolicy: Never ?

### ISSUE THREAD

**Issue by 3deep5me** [planetscale/vitess-operator#639]
Hi Folks,

I was working through the Quick-Start guide and noticed that in the [operator-latest](https://raw.githubusercontent.com/planetscale/vitess-operator/refs/tags/v2.14.0/test/endtoend/operator/operator-latest.yaml) configuration, the imagePullPolicy for the deployment is set to Never. This prevented me from running the deployment. Is this intentional?

```
Events:
  Type     Reason             Age               From               Message
  ----     ------             ----              ----               -------
  Normal   Scheduled          27s               default-scheduler  Successfully assigned vitess-operator/vitess-operator-6f87b84f88-c7c8x to node-pool0-0
  Warning  ErrImageNeverPull  0s (x4 over 27s)  kubelet            Container image "vitess-operator-pr:latest" is not present with pull policy of Never
  Warning  Failed             0s (x4 over 27s)  kubelet            Error: ErrImageNeverPull
```

**Comment by frouioui** [comment]
Hi @3deep5me, operator-latest is a test file and is only used by our E2E tests. The purpose of this yml file is to test the changed made to vitess-operator in a Pull Request, which is why the image is `vitess-operator-pr:latest`. This is an image that we load into the Kind cluster after having built the new Docker Image for vitess-operator using the PR's code.

By default, this file is not meant for experimentation or production. You can however tweak the file to use the correct Docker Image and have the proper image pull policy.

**Comment by frouioui** [comment]
I am going to close this for now, but please re-open if you have more concerns.

**Comment by 3deep5me** [comment]
Hi, thanks for your reply. 
I forgot to mention that it part of the docs. 
https://github.com/planetscale/vitess-operator/blob/main/docs/aws-quickstart.md#step-1-download-the-operator-and-example-database-configuration-files
Are you open for a MR to add a notice about it, or add somewhere else a kustomize patch for it?
