### ISSUE TITLE
 pod has unbound immediate PersistentVolumeClaims

### ISSUE THREAD

**Issue by fanux** [planetscale/vitess-operator#98]
So how to create PV for vitess operator, the [document](https://vitess.io/docs/get-started/operator/) Prerequisites not say that..

**Comment by fanux** [comment]
no persistent volumes available for this claim and no storage class is set.

**Comment by enisoc** [comment]
We recommend running with a [dynamic volume provisioner](https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/), which is why we don't mention manually creating PVs. If you have a dynamic provisioner but it's not acting on the default [Storage Class](https://kubernetes.io/docs/concepts/storage/storage-classes/) (or there is no default Storage Class), you can set `storageClassName` in the `dataVolumeClaimTemplate`.

If you don't have a dynamic volume provisioner, you can manually provision [Persistent Volumes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/) just like you would for any other PVC. The `dataVolumeClaimTemplate` supports all the fields of a PVC Spec, so you can set it to select the manually-provisioned PVs.

**Comment by fanux** [comment]
OK, I got it, I think we should add some docs in Prerequisites.
